use_frameworks!

platform :ios, '10.0'

target 'CalculatorPodsSDK_Example' do
  pod 'CalculatorPodsSDK', :path => '../'

  target 'CalculatorPodsSDK_Tests' do
    inherit! :search_paths

    
  end
end
